version: 2

sources:
  - name: user_events
    database: tbc_events
    schema: user_events
    tables:
      - name: user_registration
        columns:
          - name: timestamp
          - name: event_name
          - name: user_id
          - name: age
          - name: masked_email
          - name: preferred_language
          tests:
            - not_null
      
      - name: sign_in_events
        columns:
          - name: timestamp
          - name: event_name
          - name: user_id
            tests:
              - not_null
      
      - name: sign_out_events
        columns:
          - name: timestamp
          - name: event_name
          - name: user_id
          tests:
            - not_null


  - name: item_events
    database: tbc_events
    schema: item_events
    tables:
      - name: item_view_events
        columns:
          - name: timestamp
          - name: event_name
          - name: item_id
          - name: user_id
          tests:
            - not_null


  - name: cart_events
    database: tbc_events
    schema: cart_events
    tables:
      - name: added_to_cart_events
        columns:
          - name: timestamp
          - name: event_name
          - name: item_id
          - name: user_id
          - name: cart_id
      - name: checkout_events
        columns:
          - name: timestamp
          - name: event_name
          - name: user_id
          - name: cart_id
          - name: payment_method
          tests:
            - not_null