version: 2

models:
  - name: consumer_registration
    description: "Raw consumer registration events"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: consumer_sign_in
    description: "Raw consumer sign-in events"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: consumer_sign_out
    description: "Raw consumer sign-out events"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: item_view_events
    description: "Raw item view events"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: item_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: add_to_cart_events
    description: "Raw add to cart events"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: item_id
        tests:
          - not_null
      - name: cart_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null

  - name: checkout_events
    description: "Raw checkout events"
    columns:
      - name: user_id
        tests:
          - not_null
      - name: cart_id
        tests:
          - not_null
      - name: timestamp
        tests:
          - not_null
